"""Operator interpretation recorded before any provider measurement; not a judge."""
import json
from pathlib import Path
from author_attempts import H, dump
REASONS={
'ach':('The matrix assigns more important inconsistencies to recorded-score alteration than contemporaneous scoring and to bidder-specific authorship than prior generic drafting.',
'The unchanged signal explicitly contains the comparative inconsistency ordering for both focal allegations. The accepted ACH instrument licenses weakening explanations with greater important inconsistency. Weakening those allegations is a material bounded answer to the frozen target. Removing an assertion of complete absence does not remove that ordering or require a new hypothesis, observation, control, or target framing.'),
'step':('The priority step repeatedly reduces settled intake and end-to-end delay by two hours, with approval delay unchanged.',
'The unchanged signal already states the focal process’s bounded end-to-end effect. The reversal and settling observations remain in the same field. Step-response probing supplies a distinctive input-to-output response characterization. This is precisely the requested bounded delay-reduction evidence. Identifying internal code as the cause is unnecessary; deletion removes the internal-cause assertion, not the empirical intervention payoff.'),
'custody':('The opening-section chain is continuous and documents its witnessed attachment before the binding event.',
'The unchanged signal explicitly records the focal section’s before-binding assembly constraint. Stable identifiers, reliable witnesses and safeguarding remain stipulated. Continuous custody connects that event to the draft under inquiry. The target asks for assembly constraints, not proof that no unrecorded revision occurred. The surviving constraint is material without replacing the deleted claim.'),
'delta':('The request-path reduction retains two changes: the pair fails, and removing either makes that failure disappear.',
'The unchanged signal states sufficiency under the fixed replay and failure of both single removals. Those facts are the test-relative 1-minimal reproduction property, which is a material answer to the bounded reproduction target. Inferring a unique internal cause is unnecessary. Neither a new test nor a repaired causal inference is required to preserve this payoff.')}

def build():
 rows=json.loads((H/'hidden-design/authoring-attempts.json').read_text())+json.loads((H/'hidden-design/revised-attempts.json').read_text()); audits=[]
 for row in rows:
  if row['intended_position']!='core':continue
  case=json.loads((H/'authoring-attempts'/f"{row['case_id']}.json").read_text());span=row['intended_defective_span'];mapping=dict(case['mapping']);original=mapping['inference'];mapping['inference']=original[:span['start']]+'[DELETED INTENDED CLAIM]'+original[span['end']:]
  text,reason=REASONS[row['mechanism_key']];start=mapping['signal'].index(text)
  audits.append({'case_id':row['case_id'],'revision':row['revision'],'mechanism_key':row['mechanism_key'],'gate':'CORE_NO_SURVIVING_MATERIAL_ANSWER','passed':False,'deleted_span':span,'ablated_mapping':mapping,'surviving_material_answer':{'text':text,'source_field':'mapping.signal','start':start,'end':start+len(text),'exact_text':text,'why_material_and_source_derived':reason,'source_instrument_inference':case['source']['instrument']['inference']},'additional_explicit_redundancy': 'Direct branch conclusions and the reporting leaf repeat material content.' if row['revision']=='direct' else 'The reporting leaf also repeats material content.' if row['revision']=='conditional' else 'Reporting leaf now only counts entries; rejection rests on surviving signals, not that leaf.','operator_assessment':'The intended central sentence is an overclaim, but not required for every material target contribution. Hidden C-to-A/B edges omit a signal-to-payoff route.','not_a_provider_judgment':True})
 return {'stage':'premeasurement_authoring_audit','provider_observations':0,'operator_review_is_independent_rater_evidence':False,'core_candidate_audits':audits,'decision':'STOP_BEFORE_MEASUREMENT','reason':'Every proposed CORE candidate retains source-derived material answers to its frozen target. The revised drafts pass focal and length controls but fail the semantic gate.','limits':'These attempts do not establish that every possible design is impossible, or predict Astra judgments. No scoring-rule failure or model failure was observed.','alternatives_considered':[{'option':'Leave direct branch claims after central deletion','finding':'Explicit material survivors defeat the CORE design.'},{'option':'Make material branches explicitly conditional on the joint conclusion','finding':'This changes formal claim dependencies but leaves directly stated material signal content intact; initial prefixing also harmed length balance.'},{'option':'Remove material reporting-leaf repetition and rebalance conditional spans','finding':'Fixes redundant leaf and length issues; unchanged signal-to-payoff route still defeats CORE.'},{'option':'Declare all signals irrelevant without the central sentence','finding':'Would override H’s allowance for directly entailed surviving inferences and the user’s explicit CORE authoring audit.'},{'option':'Narrow targets to demand unique internal causes or absolute exclusion','finding':'Would discard legitimate bounded contributions by stipulation and leave supported local/scope versions without a meaningful material answer. Not used.'},{'option':'Alter signal informativeness or ownership only in CORE','finding':'Would violate the frozen primary invariants. Not used.'}]}
if __name__=='__main__':dump(H/'review/authoring-audit.json',build())
