"""Deterministic operator authorship; never reads provider results. Frozen before measurement."""
import hashlib, json, random, subprocess
from pathlib import Path
import yaml
HERE=Path(__file__).resolve().parent;ROOT=HERE.parent.parent
SEEDS={'identities':20260928041,'validity':20260928042,'anti_collapse':20260928043}
SOURCES={'diagnosis':'clinical-diagnosis--differential-diagnosis','monitor':'clinical-diagnosis--serial-monitoring','corroboration':'intelligence-analysis--source-corroboration','inverse':'seismology-geophysics--seismic-tomography','probe':'forensic-investigation--luminol-latent-trace-detection','reduction':'software-debugging-testing--delta-debugging','alignment':'dendrochronology-paleoclimate--crossdating'}
def write(path,value):
 path.parent.mkdir(parents=True,exist_ok=True)
 with path.open('x') as f:f.write(json.dumps(value,indent=2,ensure_ascii=False)+'\n')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def row(source,state,operation,signal,inference,limit,decomposition,next_inquiry,rule,framing):
 return dict(source=source,state=state,operation=operation,signal=signal,inference=inference,limit=limit,decomposition=decomposition,next_inquiry=next_inquiry,rule=rule,framing=framing)
CONTEXTS={
'T01':[
'Synthetic incident: checkout latency rose after three independently switchable deployed changes. In an isolated staging replay, workload, cache preparation and resource allocation can be restored exactly. Revision history associates each change with one of three processing stages. Representative traces, ordinary rollback/reintroduction, counters and candidate-cause tests are available to every procedure.',
'In the stipulated replay regime, excess end-to-end delay is the sum of stable nonnegative contributions of the stages traversed. This relation and the route membership are independently established target facts, not inferred from an analogy. Three routes traverse stages (1,2), (2,3), and (1,3); repeat measurements have supplied finite uncertainty bounds. No direct per-stage excess-delay counter is available in this fixture. Its absence does not make ordinary tracing non-native.',
'All procedures can access these route measurements, the route matrix, old/new revision replays, six additional route/revision tests and an ordinary confirmation replay. A contribution estimate addresses only this replay regime; identifying an affected stage constrains its associated change, and a controlled old/new comparison can test contribution. Neither ensures unique root cause or live-load generality.'
],
'T02':[
'Synthetic procurement inquiry: three retained accounts are deliberate steering, legitimate specialization, and clerical reuse. Authenticated tender versions, scoring sheets, emails and witness records permit ordinary dated chronology, source-dependence checks and corroboration. No account is stipulated true.',
'Three accessible additional records have a frozen response dictionary derived from stipulated administrative rules: R1 can distinguish steering from the other two accounts, R2 can distinguish specialization from the other two, and R3 has three mutually exclusive recorded values, each inconsistent with two accounts. Administrative validation establishes those response predictions only for this retained hypothesis set. A response outside the dictionary leaves the comparison unresolved; it must not be forced into a predicted category.',
'The budget is one additional record request followed by ordinary authentication/corroboration. Existing records and the response dictionary are equally available to all four procedures. The native discretionary request would be R1 because it concerns the most prominent allegation. R3 is equally accessible and has no cost or ethical disadvantage. A fixed record identifier order resolves any selection tie.',
'There are also authenticated ordered monthly procurement registers with missing entries, independent date anchors, and documented common administrative events affecting their recorded counts. An alignment can constrain when a restriction appeared, but cannot itself establish intent or steering; that requires independently corroborated content already supplied in the inquiry.'
],
'T03':[
'Synthetic manuscript inquiry: witnesses, visible variants, joins, paper features and dated correspondence support several revision/assembly accounts. A visibly overwritten patch may preserve erased ink; ordinary reading does not reveal it. No prior reading or unique chronology is stipulated.',
'An available bounded micro-probe elicits a localized response from a particular erased ink component. Its sensitivity range, blanks, known positives, interfering materials and possible damage to later analysis are documented in target evidence. Responsive location is only presumptive material detection; it is not proof of a particular former reading, author or date.',
'A separate already supplied overlay relation establishes that any detected underlayer at this patch precedes its visible overwriting. Independent collation is available to investigate a recovered reading; only independently justified correspondence can date it. Each procedure has the same access to the probe, witnesses and controls. The budget permits a control-checked patch assay and one adjacent-patch or witness follow-up.'
],
'T04':[
'Synthetic approval workflow: ticket histories, queues, staffing, interviews and repeated total route times are available. Known routes pass through approval stages (1,2), (2,3), and (1,3). Within matched case type, staffing and demand, controlled calibration establishes additive stable stage waiting contributions with bounded timestamp error. Direct internal timestamps are unavailable in this fixture; ordinary timestamp comparison remains native practice.',
'All procedures can use the same route membership and total timings, including repeated observations and uncertainty bounds. Several nonnegative stage assignments may fit within those bounds. The route model applies only to this matched regime, not every organizational process.',
'The budget permits two additional route observations and one ordinary sandbox pilot of a candidate handoff change with a matched unchanged comparison. Estimating hidden waits can provide a bounded answer about where delay accumulates; it does not establish which live organizational remedy will work. Existing ownership and workflow records map each inferred stage to a handoff.'
],
'T05':[
'Synthetic onboarding proposal: six independently switchable interface/rule elements and their dependencies are specified. A resettable replay of a fixed consented usability task supplies a deterministic pass/fail oracle for activation blockage, with unresolved outcomes explicitly possible outside the defined valid configurations. Baseline full configuration reproducibly fails; removing every optional element passes. Deletions preserve a runnable flow only when listed dependency constraints hold.',
'Every procedure has the same user-error notes, funnel observations, oracle, valid-deletion rules and budget of 80 replay tests. No deletion monotonicity or unique minimal explanation is assumed. Elements can interact; multiple failure-preserving subsets may exist. A fixed identifier order is available for reproducible deletion trials.',
'Failure means inability to complete this recorded activation task, not real-user population rejection. A failure-preserving subset and the pass results of its valid one-element deletions give bounded evidence about interactions and test-relative necessary elements within that subset, not global feature rankings or universal necessities.'
],
'T06':[
'Synthetic correspondence bundle: custody, postmarks, dated event mentions, handwriting and material clues permit ordinary provenance checks and a partial chronology. Ordered references to annual administrative events can be compared with independent calendars, with repeated events left ambiguous.',
'Each letter also carries a measured sequence of impression counts from a documented annually advanced office device. Independent maintenance records establish the increment period, common disturbances across devices and possible omitted or duplicated impressions. Long overlapping reference sequences and independent dated anchors are supplied; these are measured records, not imaginary signals. They do not uniquely determine an offset by stipulation.',
'All procedures can inspect the same count sequences, calendars, material and provenance records. Distinctive runs, repeated runs and gaps are present. A documented impression-to-letter relation bounds writing to the associated interval; impression order alone cannot identify author or event intent. The budget permits one full alignment comparison and one independent-anchor check.'
]}
DATA={}
DATA['T01']=[
row('diagnosis','Three deployed changes and workload variation are candidate contributors to a new regression.','List the competing explanations; compare symptoms in traces, counters and matched replay tests; weaken explanations contradicted by observations.','Each candidate agrees or conflicts with observed latency, workload and replay behavior.','Retain supported candidate contributions and explicitly unresolved alternatives; temporal association alone does not identify a cause.','Confounding, incomplete explanations and unrepresentative replay limit attribution.','Ordinary candidate causes: deployed changes, load and configuration.','Use ordinary discriminating replay or rollback/reintroduction, then check whether the regression returns under comparable conditions.','No new rule; ordinary hypothesis/test debugging.','Treat the checkout service as a febrile patient; read telemetry as vital signs and deployed changes as rival etiologies in a clinical differential.'),
row('diagnosis','Three deployed changes and workload variation are candidate contributors to a new regression.','Perform the same competing-explanation and replay comparison, recording every candidate/test match or conflict in a matrix; record unresolved cells explicitly.','The same latency, workload and replay observations are indexed by candidate and test.','Retain supported candidate contributions and unresolved alternatives using the same evidential logic as ordinary debugging; table completeness is not extra evidence.','Confounding, incomplete explanations and unrepresentative replay limit attribution.','Ordinary candidate causes recorded as matrix rows.','Use ordinary discriminating replay or rollback/reintroduction, then check recurrence; the matrix imposes no new test-selection or stopping rule.','B adds recording structure only.','Organize the clinical differential in a symptom-by-etiology chart.'),
row('inverse','The same candidate table and calibrated route measurements describe a regression with hidden stage contributions.','Use the candidate/test matrix. Compare the observed totals of all three known routes with sums predicted by candidate nonnegative stage contributions, adjust those contributions to fit, and retain every assignment consistent with the measurement bounds.','Across-route discrepancies and the set of stage contributions compatible with all measured totals.','Compatibility across overlapping routes constrains hidden stage contributions even without direct stage counters. Map constrained stages to their associated deployed changes as bounded candidate contribution evidence; do not infer a unique live cause.','The calibrated additive regime, route coverage, error and non-uniqueness bound the inference. A contribution interval containing zero cannot establish a nonzero contribution.','Keep ordinary deployed-change alternatives; stage variables are the operands required by the one inverse-constraint rule.','Use the same ordinary old/new replay or rollback confirmation for an implicated change; no new adaptive acquisition rule is added.','B→C adds only the overlapping-route inverse warrant, with its required residual calculation and fit set.','Read the path residuals as travel-time anomalies through a hidden interior, using the source inverse measurement chain.'),
row('inverse','The calibrated route model and ordinary candidate table describe multiple possible internal contributors.','Fit bounded nonnegative stage contributions to overlapping-route timings. Examine residual structure; select an available additional route that separates remaining assignments, refit, and compare the implicated stage under its associated old/new deployed change with controlled reset.','Compatible assignments, route residuals, reduction of ambiguity after the selected route and controlled old/new contribution changes.','The joint constraints localize bounded contributions; discrimination-directed route selection tests unresolved structure and the controlled revision comparison tests the associated change within the replay.','Model misspecification, coverage, finite uncertainty and replay generalization remain limits; residual patterns are not automatic proof of a hidden mechanism.','Represent hidden stages jointly, distinguish model mismatch from weak coverage, and connect only independently documented stage/change associations.','Select the next route from unresolved assignments; stop additional probing at the six-test budget or when no available route separates them, then report surviving alternatives and confirmation limits.','D adds adaptive measurement, model-mismatch review and targeted attribution confirmation.','Reconstruct the hidden interior from multiple traversals, then illuminate the unresolved region with another ray.')]
DATA['T02']=[
row('corroboration','Claims about procurement steering are supported or challenged by documents and witnesses with known provenance and possible dependence.','Trace provenance and independence, compare the same bounded claim across sources, and investigate contradictions before reporting corroboration.','Independent agreements, disagreements and copying relationships among records.','Converging independent evidence strengthens a bounded claim; dependent repetition does not independently confirm it.','Common origin, authentication gaps and corroborated facts short of intent limit conclusions.','Ordinary claims, sources and dated events.','Request R1 and authenticate it, seek disconfirmation and report remaining uncertainty.','No new rule; ordinary corroboration.','Operate an intelligence fusion cell: separate independent sensors from echo networks before fusing the target dossier.'),
row('corroboration','The same claims and source-dependence information are available.','Perform ordinary provenance, independence and contradiction checks, recording claims by source in an explicit matrix and documenting unresolved cells.','The same independent agreements, disagreements and copying links recorded in a table.','Use the same bounded corroboration logic; the matrix supplies no additional warrant.','Common origin, authentication gaps and incomplete evidence of intent remain limits.','Ordinary claims, sources and dates as matrix entries.','Request R1 and authenticate it; no new acquisition rule is imposed by completing the matrix.','B adds structured recording only.','Use a sensor-by-claim fusion grid for the same independent-source checks.'),
row('corroboration','The same claim/source matrix, three surviving accounts and validated record-response dictionary are available.','Assess provenance, independence and contradictions. For each accessible record, count surviving accounts for each predicted response, take its largest survivor count, and request the record with the smallest such count; resolve ties by record identifier. Authenticate and compare the returned record by ordinary corroboration.','The ordinary authenticated record response, its consistency with the accounts, and any source dependence.','Apply ordinary bounded corroboration and disconfirmation; a response outside the dictionary is unresolved, not proof that every account is false.','The selection rule depends on the supplied finite account set and response dictionary; hidden accounts, dependence or unpredicted responses limit interpretation.','Keep ordinary claims and the same competing accounts; no new historical reconstruction units.','The fixed worst-case-discrimination rule selects R3 instead of discretionary R1; after that single allowed request, retain the ordinary authentication and reporting follow-up.','B→C changes only the next-record selection constraint; actions, evidence types and corroboration warrant remain ordinary.','Direct the next sensor task by the least ambiguous worst-case hypothesis split, then use the same fusion discipline.'),
row('alignment','Authenticated ordered registers share documented administrative influences, uncertain placement, gaps and independent anchors.','Compare long ordered register patterns at competing offsets, explicitly represent missing increments, require consistency across overlaps and anchors, then request the available record that best discriminates surviving steering-related chronology accounts. Authenticate it independently.','Repeated aligned patterns, unmatched increments, competing offsets and an independently checked discriminating record.','Consistent alignment constrains the timing of a restriction; independently corroborated content supplies the separate bridge to the steering question. Alignment alone does not prove intent.','Repetition, gaps, unreliable anchors and alternative accounts can leave offsets or intent unresolved; no absence is automatically concealment.','Jointly represent temporal increments, competing offsets and the distinct question of intent.','Choose the discriminating request among unresolved accounts, respect the one-record budget and preserve alternate chronologies.','D adds ordered reconstruction, explicit missing increments and cross-record consistency to targeted inquiry.','Crossdate the administrative growth rings, retaining false rings and missing seasons as competing alignments.')]
DATA['T03']=[
row('diagnosis','Several revision/assembly explanations account for unusual phrases, visible deletions and manuscript joins.','List competing revision accounts; compare visible variants, material features and dated correspondence, and weaken accounts inconsistent with those observations.','Compatibility and conflict between the accounts and ordinary manuscript evidence.','The observations constrain candidate revision sequences; an unusual phrase is not itself proof of a hidden prior state.','Missing witnesses, shared copying and ambiguous material dating limit sequence claims.','Ordinary revision accounts and witness comparisons.','Collate another witness or inspect relevant dated correspondence, retaining unresolved accounts.','No new rule; ordinary comparative manuscript reasoning.','Diagnose the manuscript as a stratified patient: lexical lesions are symptoms and rival formation histories are etiologies.'),
row('diagnosis','The same revision accounts, visible variants and dated witnesses are available.','Catalogue visible anomalies and compare them against revision accounts in an explicit matrix using the same ordinary disconfirmation logic.','The same visible variants, material clues and correspondence indexed by anomaly and account.','Use ordinary compatibility/conflict to constrain sequence; a complete catalogue does not independently reveal a previous state.','Missing witnesses, copying dependence and ambiguous dating remain limits.','Ordinary witnesses and revision accounts in a systematic catalogue.','Collate another witness or consult correspondence; the catalogue adds no new stopping or evidence rule.','B adds catalogue structure only.','Tabulate the manuscript symptoms in a diagnostic chart.'),
row('probe','The same manuscript comparison includes a patch with a possibly persistent erased underlayer and documented probe behavior.','Maintain the anomaly catalogue. Apply the available probe within documented damage limits, compare the localized response with its blanks and known positives, and record response or nonresponse.','An otherwise invisible localized material response, plus blank and positive-control responses.','A response supports presence/location of responsive material, not a particular past event. The separately supplied overlay relation makes an actual underlayer a bounded pre-overwriting constraint; identifying or dating a reading requires independent evidence.','Interfering materials can respond; degradation can prevent response; damage limits apply. Nonresponse is not proof of no prior writing.','Keep ordinary patch, witness and revision-account units; no new complete-history model.','Return to ordinary witness collation or correspondence with the localized finding; no new follow-up-selection rule.','B→C adds one selective assay action and its inseparable detection signal/warrant.','Use the latent-trace reagent to reveal a presumptive residue beneath the visible textual surface.'),
row('probe','Competing local earlier-state accounts predict different responsive locations within the same permitted assay region.','Predict locations from each account, apply the selective assay with blanks/positives and interference checks, compare the resulting response pattern with those predictions, and choose the single permitted adjacent-patch or witness follow-up that distinguishes surviving accounts without destroying needed material.','Controlled localized responses, inconsistent predicted locations, ambiguous interference and independently collated witness features.','Presumptive detection constrains material presence; only independent overlay and witness evidence connect that finding to a bounded revision account. Neither detection nor nonresponse proves an entire history.','False positives, sensitivity, damage, missing witnesses and nonunique histories remain explicit.','Separate detection, local-state alternatives and independent chronological reconstruction.','Choose the discriminating nondestructive follow-up, stop at the assay/follow-up budget and report surviving states without invented dates.','D coordinates state predictions, selective detection, interference handling and discriminating follow-up.','Reconstruct a bounded latent-trace scene while separating presumptive reactions from event attribution.')]
DATA['T04']=[
row('monitor','An approval process has repeated turnaround and queue observations under known staffing and demand.','Compare repeated handoff and total-route timings with earlier comparable periods, noting persistent or changing delays and relevant staffing or demand changes.','Stable, rising or falling delay and queue patterns over time.','The trajectory supports bounded assessment of persistence or change; a timing trend alone does not identify its cause.','Sampling, demand confounding and changing case mix limit generalization.','Ordinary handoffs, queues and case types.','Inspect delayed cases and pilot a bounded handoff change with a matched comparison.','No new rule; ordinary process monitoring.','Read the organization as a patient under serial vital-sign surveillance: queue pressure and circulation time describe its hemodynamic course.'),
row('monitor','The same route timings, queues and staffing records are available.','Perform ordinary repeated timing comparison and record every route, ownership handoff and delay in a systematic map and time table.','The same persistence and change patterns across comparable periods.','Use ordinary process-monitoring inference; a more complete map is not a new causal warrant.','Sampling, case mix and staffing confounding remain limits.','Ordinary handoffs and routes recorded in a complete table.','Inspect exceptions and pilot a bounded change with a matched comparison; no additional selection constraint.','B adds systematic map/recording only.','Construct an explicit vital-sign chart of the organizational circulation.'),
row('inverse','The same route map and total timings describe hidden stage waiting contributions in the calibrated matched regime.','Use the route map. Predict each route total from candidate nonnegative stage waits, compare with all measured route totals, adjust the waits and retain every assignment within the supplied error bounds.','Joint route residuals and compatible intervals for hidden stage waits.','The overlap constraints bound contributions of the mapped handoffs without direct internal timestamps. This answers a bounded localization part of the task; it does not establish a remedy.','Calibration, route coverage, error and non-uniqueness limit localization; do not infer a nonzero wait if its compatible interval includes zero.','Keep mapped handoff units; jointly estimated wait variables implement the one new inverse warrant.','Use the same ordinary matched sandbox pilot for a candidate handoff change and report observed turnaround, without claiming live generality.','B→C adds only the overlapping-route inverse warrant and its necessary fit calculation.','Use travel-time anomalies to constrain the organization’s hidden interior.'),
row('inverse','The calibrated route system may leave hidden contributions nonidentifiable and may have model mismatch.','Fit compatible waits, inspect structured residuals, choose up to two accessible routes that separate unresolved assignments, and refit. Distinguish persistent model mismatch from weak route coverage. Then run the ordinary matched sandbox pilot for an implicated handoff.','Changes in compatible assignments, residual structure, route discrimination and matched pilot turnaround.','New route constraints test unresolved internal structure; the separate pilot supplies bounded evidence about a candidate change, not proof of a unique cause.','Finite error, model assumptions, insufficient route geometry and regime dependence remain explicit.','Separate hidden waits, observation coverage and possible model mismatch.','Acquire routes for identifiability rather than volume; stop at two or when none distinguishes assignments, then select and report the bounded pilot.','D adds identifiability-directed acquisition, residual interpretation and targeted follow-up.','Design crossing rays to illuminate unresolved regions, then test the implicated handoff.')]
DATA['T05']=[
row('diagnosis','Activation fails in the full onboarding proposal and several element/dependency explanations are plausible.','List competing explanations, inspect user errors and dependencies, and compare ordinary staged prototype variants using the supplied replay oracle.','Variant pass/fail observations and user-error patterns compatible or incompatible with each explanation.','Narrow plausible reasons for blocked activation under this task; ordinary variant comparison does not certify a globally minimal explanation.','Interactions, limited tasks and unresolved invalid configurations limit feature-necessity claims.','Ordinary features, user needs and dependency hypotheses.','Test another plausible staged variant or revise a suspected interaction based on observed errors.','No new rule; ordinary proposal diagnosis.','Perform a clinical differential of the proposal’s activation syndrome.'),
row('diagnosis','The same failing proposal, dependencies, oracle and candidate explanations are available.','Enumerate reasons for failure in a table and systematically record pass/fail and user errors for ordinary staged variants.','The same task outcomes and explanation compatibility recorded explicitly.','Use ordinary variant-comparison inference; enumeration alone does not establish minimality or a feature ranking.','Interactions, task dependence and unresolved configurations remain limits.','Ordinary feature/dependency explanations as table rows.','Select another plausible staged variant; the table imposes no failure-preserving reduction criterion.','B adds explicit enumeration and recording only.','Complete the differential chart without changing the clinical logic.'),
row('reduction','The same reproducibly failing configuration has valid removable elements and the resettable oracle.','Run failure-preserving reduction trials: in fixed identifier order try each valid one-element deletion, retain a deletion only when failure recurs, restart from the retained reduced configuration, and stop after a complete pass accepts no deletion or the 80-test budget is exhausted.','Which reduced configurations still fail, which pass and which are unresolved.','The retained subset reproduces failure. A completed final pass establishes one-deletion minimality among valid deletions under this oracle; a budget stop supports only a reduced sufficient subset. This exposes test-relative interactions, not global necessity or a unique cause.','Do not assume monotonicity, treat unresolved as failure, or generalize beyond valid deletions and this task; multiple minimal subsets can exist.','Replace feature-by-feature priority as the explanatory unit with the retained failure-preserving subset and its tested deletion boundary.','The next trial is the next valid deletion from the currently retained failure case; ordinary follow-up examines its observed interaction after the reduction ends.','B→C adds one reduction/minimality criterion; adaptive trials and bounded minimality are its coupled consequences.','Simplify the failure-inducing input while preserving the oracle’s observed failure.'),
row('reduction','The same failing configuration, dependency constraints and oracle support repeated reductions.','Partition elements, test valid removals and complements, retain failure-preserving reductions, refine partitions when blocked and finish with all valid one-element deletions. Independently recheck the retained failure and selected interaction boundaries within the 80-test budget.','Failing subsets, passing deletions, unresolved trials and repeated interaction-boundary outcomes.','A reproducible retained subset is sufficient for this failure; only a completed deletion check supports one-deletion minimality. Complement and interaction tests distinguish alternative local explanations without global minimum or unique-root-cause claims.','Dependencies, unresolved outcomes, multiple minima and exhausted budget restrict conclusions.','Represent configurations, deletion boundaries and interactions rather than a single feature ranking.','Choose the next partition/complement from remaining reduction uncertainty, prioritize unresolved interaction checks and report the exact achieved minimality at budget stop.','D coordinates partition reduction, reproducibility, interaction checks and adaptive follow-up.','Run a full failure-inducing-input reduction with explicit oracle and minimality boundaries.')]
DATA['T06']=[
row('alignment','Ordered dated-event references in letters overlap an independently dated calendar, with some repeated events.','Compare the order of referenced events across letters and the calendar, shifting candidate placements until distinctive known event patterns correspond; retain alternative placements where events repeat.','Matching event sequences and conflicts with ordinary independent date clues.','Compatible anchored event patterns constrain ordinary relative order and date intervals; a repeated event alone is not a unique anchor.','Short/repeated sequences, erroneous references and missing events limit dating.','Ordinary letters, referenced events and candidate date intervals.','Cross-check an independent postmark or dated reference and retain ambiguous intervals.','No new rule; ordinary anchored chronology and pattern comparison.','Crossdate the bundle’s annual growth rings against the master chronology; retain false rings and missing seasons as documentary ambiguities.'),
row('alignment','The same letters, calendar sequences and independent date clues are available.','Make the ordinary ordered-event comparison explicit in a table of candidate dates, references and compatible placements; record more of the already available ordinary clues.','The same anchored pattern matches and dating conflicts in structured form.','Use ordinary date triangulation and ordered-pattern comparison; table size adds no dating warrant.','Repeated references and unreliable anchors remain ambiguous.','Ordinary letters, event mentions and date intervals in a table.','Check the same independent anchor and preserve unresolved intervals; no new alignment constraint.','B adds structured comparison only.','Lay out the ordinary growth-ring crosschecks in a master chart.'),
row('alignment','The same bundle also supplies measured, overlapping impression-count sequences with documented annual increments and common disturbances.','Triangulate dates and shift the long ordered count patterns against overlapping references, explicitly test omitted/duplicated increments, and record alignments that satisfy the supplied measurement tolerance and independent anchors.','Relational matches across long count runs and missing/extra increments required to reconcile them, including nonunique compatible alignments.','The measured alignment constrains increment positions; the independently documented impression-to-letter relation supplies only its bounded writing interval. A gap is an observed alignment requirement, not automatically an intentional omission.','Repeated patterns, measurement error, weak shared disturbance, uncertain anchors and nonunique gaps limit dating.','Keep letter dating as the task; increment positions are the measurement units needed for the one new relational observable.','Return to ordinary independent-anchor checking and report alternative intervals; no new adaptive request rule.','B→C adds a measured relational observable, with its necessary alignment operation and bounded warrant.','Read the long measured increment pattern and its missing rings, beyond the familiar event calendar.'),
row('alignment','Several long count sequences overlap, contain possible omitted/duplicated increments and admit competing offsets.','Construct competing offset/gap assignments jointly across all overlaps, reject assignments inconsistent with measurement bounds or independent anchors, and choose the one allowed anchor check where surviving chronologies differ. Recheck global consistency after that observation.','Jointly compatible offsets, gap patterns, anchor conflicts and remaining alternative chronologies.','Repeated global correspondence and independent anchors constrain chronology; unresolved fits remain alternative intervals rather than a forced date. The impression-to-letter bridge stays separately bounded.','Correlated disturbance, reference error, weak overlap and nonunique alignments remain possible; no chronology proves authorship or intention.','Joint chronology variables, gap alternatives and independent anchors replace isolated letter-by-letter decisions.','Use the permitted anchor check to distinguish surviving assignments, then stop and report global consistency and residual ambiguity.','D coordinates joint alignment, competing gaps, independent anchoring and targeted inquiry.','Crossdate overlapping specimens into a globally checked master chronology without forcing a unique fit.')]
for _tid in CONTEXTS:
 CONTEXTS[_tid]=[x.replace('oracle', 'repeatable task test') for x in CONTEXTS[_tid]]
 for _row in DATA[_tid]:
  for _key in ('state','operation','signal','inference','limit','decomposition','next_inquiry'):
   _row[_key]=_row[_key].replace('oracle', 'repeatable task test')
PRIMARY={'T01':'inferential_warrant','T02':'next_inquiry','T03':'action','T04':'inferential_warrant','T05':'problem_decomposition','T06':'observable'}
def main():
 ids=[f'N{i:03}' for i in range(1,25)];random.Random(SEEDS['identities']).shuffle(ids)
 manifest=[];audits=[];baseline_commit=subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT).decode().strip()
 for tid,ladder in DATA.items():
  base=json.loads((HERE/'baselines'/f'{tid}.json').read_text())
  write(HERE/'contexts'/f'{tid}.json',{'facts':CONTEXTS[tid],'authorship':'Operator-authored synthetic stipulations, not measured target-world evidence.'})
  for level,data in zip('ABCD',ladder):
   cid=ids.pop();source_path=ROOT/'instruments'/f'{SOURCES[data["source"]]}.yaml';src=yaml.safe_load(source_path.read_text());assert src['extraction']['status']=='accepted'
   # The operational chain is identical in both forms. Framing prefixes alone are removed.
   core={k:data[k] for k in ('state','operation','signal','inference','limit')}
   core['operation']+=' Next inquiry: '+data['next_inquiry']
   core['state']+=' Decomposition: '+data['decomposition']
   framed={**core,'state':data['framing']+' Operational target state: '+core['state']}
   case={'case_id':cid,'source':{'name':src['extraction']['name'],'practice':src['extraction']['practice'],'instrument':src['instrument']},'target':{'domain':base['target_domain'],'question':base['target_task'],'evidence':CONTEXTS[tid]},'mapping':framed}
   neutral={'procedure':'State: '+data['state']+' Procedure: '+data['operation']+' Limits and stopping conditions: '+data['limit'],'action':data['operation'],'observables':data['signal'],'inferential_warrant':data['inference'],'problem_decomposition':data['decomposition'],'next_inquiry':data['next_inquiry']}
   write(HERE/'cases'/f'{cid}.json',case);write(HERE/'neutralizations'/f'{cid}.json',neutral)
   tags=[]
   if level=='A':tags=['exotic-collapse']
   if level in 'CD':tags=['mundane-positive']
   manifest.append({'case_id':cid,'target_id':tid,'ladder_level':level,'intended_departure_type':PRIMARY[tid] if level in 'CD' else None,'design_intention':'CLEAR_COLLAPSE' if level=='A' else 'CLEAR_COLLAPSE or BORDERLINE_KEEP; not forced' if level=='B' else 'SUFFICIENT_DEPARTURE','adversary_tags':tags,'source_path':str(source_path.relative_to(ROOT)),'single_rule_or_extension':data['rule'],'baseline_commit':baseline_commit})
   audits.append({'case_id':cid,'source_mapping_sha256':sha(HERE/'cases'/f'{cid}.json'),'neutralization_sha256':sha(HERE/'neutralizations'/f'{cid}.json'),'removed_framing':data['framing'],'framing_only_removed':True,'operations_preserved':{'pass':True,'evidence':data['operation']},'signals_preserved':{'pass':True,'evidence':data['signal']},'warrants_preserved':{'pass':True,'evidence':data['inference']},'conditions_and_stopping_preserved':{'pass':True,'evidence':data['limit']+' '+data['operation']},'next_inquiry_preserved':{'pass':True,'evidence':data['next_inquiry']},'decomposition_preserved':{'pass':True,'evidence':data['decomposition']},'findings':['All operational sentences retained verbatim across corresponding fields; only the explicit source-imagery prefix is removed.','Source instrument identity and its generic source description are excluded; target-applicable limits remain.'],'audit_kind':'Operator-side textual correspondence, not independent practitioner or provider review.'})
 manifest.sort(key=lambda r:r['case_id'])
 write(HERE/'operator-manifest.json',{'seeds':SEEDS,'mappings':manifest,'intent_is_ground_truth':False,'controls':'none; neutral-only','C_design_policy':'One added rule; necessary downstream consequences can affect several fields.','adversary_policy':'Framed A imagery is deliberately conspicuous. C/D operations are plain; source-framed forms retain a removable framing prefix. Only neutral forms reach the primary judge.'})
 write(HERE/'neutralization-audit.json',{'audit_stage':'before any provider call','cases':audits,'result_informed_repairs':False,'limitations':['Same operator authors mappings and audit; textual correspondence is stronger than an independent semantic-equivalence claim.','The underlying design is purposive and synthetic.']})
 write(HERE/'ladder-audit.json',{'ladders':[{'target_id':tid,'B_to_C_rule':DATA[tid][2]['rule'],'primary_locus':PRIMARY[tid],'removal_counterfactual':'Remove that rule and return to the B procedure, retaining shared facts/resources and ordinary follow-up.','coupled_consequences':'Required measurement, representation and inference consequences of the stated rule are retained; they are not independent novelty requirements.','D_extension':DATA[tid][3]['rule'],'baseline_constraint':'Inherited practitioner scope and methods unchanged; source availability does not redefine ordinary practice.'} for tid in DATA],'caveats':['T02 deliberately tests whether a mandatory acquisition criterion exceeds native discretionary disconfirmation. It may collapse; the intention is not a verdict.','T03 probes may be familiar to some manuscript specialists; the frozen baseline and its uncertainty govern.','T05 minimality and T06 alignment couple several diagnostic fields despite one added operational rule.','T01 and T04 repeat inverse constraints in different domains; five loci do not imply five independent source mechanisms.']})
 paths=[*(HERE/'cases').glob('*.json'),*(HERE/'neutralizations').glob('*.json'),*(HERE/'contexts').glob('*.json'),HERE/'operator-manifest.json',HERE/'neutralization-audit.json',HERE/'ladder-audit.json',HERE/'author_cases.py']
 write(HERE/'ladders-freeze.json',{'baseline_commit':baseline_commit,'files':{str(p.relative_to(ROOT)):sha(p) for p in sorted(paths)}})
if __name__=='__main__':main()
