"""Post-freeze operator review. Preserves all original judgments and design intentions."""
import json, sys
from pathlib import Path
HERE=Path(__file__).resolve().parents[1];sys.path.insert(0,str(HERE))
import runner as r
NOTES={
'N010':('Candidate causes are tested against traces and controlled replay; rollback/reintroduction remains native.','Both compare the actual operation with the reliability baseline rather than treating clinical framing as departure.','No constraint survives beyond ordinary hypothesis testing; both return lossless reduction and mere explicitness.','An A design supplies a valid native anchor, not an independent ground-truth label.','Both reject. No retained A case occurs here.','This is positive evidence of collapse recognition within the explicit supplied baseline.'),
'N011':('The candidate/test matrix records the same tests and outcomes without a selection, stopping or evidence rule.','Both correctly retain baseline replay, competing causes and controlled confirmation as ordinary.','Both identify the matrix as removable bookkeeping, not a material constraint.','The B design is intentionally a formalization boundary probe, but its wording explicitly disclaims changed logic.','Both reject; this is not a demand that every B design be rejected.','The result exercises clear formalization more than genuinely ambiguous formalization; explicit author cues limit generalization.'),
'N008':('Joint overlapping-route constraints bound hidden stage contributions and preserve all error-compatible assignments.','Both distinguish the bound-set warrant from ordinary intervention, but B sometimes overstates lack of inverse-problem specialty as an exclusion of inverse methods.','The zero-compatible contribution rule constrains claims; both find material loss on native substitution.','One inverse rule has coupled action, derived-observable and warrant consequences. A marks decomposition absent; B uncertain.','Both keep as sufficient despite an unchanged ordinary confirmation step.','Supports a local inferential departure without requiring changed downstream practice; applicability remains confined to the synthetic additive regime.'),
'N007':('Joint fitting, residual inspection, assignment-discriminating routes and controlled revision confirmation are coordinated.','The final old/new comparison is native. A is uncertain whether adaptive inquiry itself exceeds ordinary discriminating testing; B marks it present.','Both identify fit consistency as material, while only B confidently treats next-route selection and stopping as independently non-native.','D retains several coordinated moves without requiring every diagnostic field to be present.','Both keep as sufficient.','Shared verdict does not resolve whether adaptive selection adds novelty independently of the inverse representation.'),
'N012':('Provenance-sensitive corroboration and the stipulated R1 request remain ordinary reporting.','Both preserve source-independence checks and bounded allegations as native.','Removing the record description loses no additional warrant, observable or acquisition constraint.','A is a valid corroboration transfer despite its removable intelligence imagery.','Both reject.','Supports recognition of native corroboration under exotic source framing removed before measurement.'),
'N006':('A claim/source matrix documents the same corroboration checks and R1 request.','Both use the baseline of native provenance, independence and contradiction handling.','No rule is attached to empty cells or matrix completion; both identify lossless reduction.','The B design preserves explicit ordinary acquisition rather than adding an operational matrix constraint.','Both reject.','A clear bookkeeping case; does not establish behavior on subtler, naturally occurring formalization.'),
'N002':('A mandatory worst-case survivor-count criterion selects R3 instead of the stipulated discretionary R1.','Both recognize native disconfirmation but distinguish the binding selection criterion within the supplied one-request setting.','The lost constraint is the required choice under identical inputs, not merely higher usefulness or a technical formula.','This C changes one independent next-inquiry rule. Both mark action and next inquiry present, warrant/decomposition absent; observable is absent/uncertain.','Both keep as sufficient; no new evidence type or interpretation warrant is required.','The strongest one-rule example, but its native R1 choice and fully discriminating R3 dictionary are favorable author stipulations. It does not show all reporters would choose R1.'),
'N024':('Joint register alignment and a discrimination-directed request coexist.','A treats alignment nativeness as uncertain and rests on selection; B treats alignment as non-native and the generic selection criterion as underspecified. B also describes native chronology too narrowly as a single dated account.','Both find material loss, but identify different losses: A the mandatory request priority; B offset/gap acceptance and consistency.','D is kept through different sufficient mechanisms; this is not a numerical or status ladder reversal.','Both keep as sufficient.','The largest mechanism disagreement: four locus statuses differ despite the same final verdict. A explicitly conditions its R3 conclusion on three accounts surviving; no realized alignment outcome is supplied.'),
'N005':('Visible variants, material clues and dated context constrain competing revision accounts.','Both regard hypothesis comparison and constrained chronology as ordinary manuscript practice.','No selective assay or altered evidence rule is performed; both identify lossless native reduction.','A framing removes clinical imagery without changing ordinary operations.','Both reject.','Supports native-collapse recognition without requiring foreign terminology to be intrinsically invalid.'),
'N001':('An anomaly catalogue indexes ordinary witness and account comparisons.','Both retain ordinary comparative manuscript inference; tabular thoroughness does not establish a new kind of reasoning.','The matrix has no added stopping, acquisition or evidence rule; both classify mere explicitness.','The B design expressly says that a complete catalogue does not reveal a prior state.','Both reject.','Another clear formalization control. The sample lacks a surviving B case on which the families disagree.'),
'N004':('A control-checked, damage-bounded assay elicits an otherwise invisible material response.','Both find the scope of native material inspection ambiguous. A explicitly separates invisibility from novelty; B also raises instrument availability, which must not itself define nativeness.','Materiality, lossless reduction and mere formalization are all uncertain in both responses. Neither converts that uncertainty into rejection.','The intended action-primary C remains one added assay, with coupled response/control consequences; the action field is uncertain in both.','Both return BORDERLINE_KEEP.','The decisive permissiveness observation: uncertainty about uncommon native instrumentation is retained. It does not demonstrate that the assay is definitively non-native.'),
'N020':('Earlier-state accounts predict response locations before controlled assay and pattern comparison, followed by bounded discrimination.','Both find the prospective controlled test more clearly beyond native inspection than C. A treats ordinary follow-up as absent departure; B leaves follow-up and decomposition uncertain.','A calls the controlled warrant present, B uncertain. Both identify non-removable prediction/control operations.','D coordinates prediction, detection, interference treatment and a follow-up without proving a whole history.','Both keep as sufficient.','B sometimes calls mismatch elimination; this must stay conditioned on sensitivity/interference, not become definitive absence or event attribution. The A/C/D progression is preserved without a numeric novelty scale.'),
'N023':('Overlapping total route timings constrain compatible hidden stage waits.','Both distinguish the inverse warrant from direct timestamp and queue comparison; the baseline is an unverified scope, and some process-mining practice could narrow the distinction.','Both find the all-compatible-assignments and zero-interval rules materially constrain localization claims.','One inverse rule affects action, derived evidence and warrant; decomposition is absent/uncertain and ordinary pilot follow-up remains absent departure.','Both keep as sufficient.','Supports local warrant retention, but the corresponding A/B cases failed validity, so this target has no measured lower-floor comparison.'),
'N019':('Compatible waits guide extra-route selection, residual interpretation and the stopping point before an ordinary pilot.','Both identify a coupled estimation/coverage/mismatch inquiry distinct from the supplied analyst baseline.','The actual constraints are assignment discrimination, limited acquisition and separating model mismatch from weak coverage.','All five loci are present in both D judgments; these are linked procedure features, not a field-count score.','Both keep as sufficient.','A concordant coordinated transfer; neither successful identification nor a working live remedy was measured.'),
'N014':('Ordinary staged variants and observed task errors narrow explanations for activation blockage.','Both recognize native prototype testing, dependencies and bounded interpretation.','No failure-preserving search or terminal minimality certificate is performed.','A is admitted and collapses; the more compressed B formulation was excluded for validity.','Both reject.','A valid native anchor survives, but B attrition prevents the planned B/C contrast.'),
'N013':('Keep deletions only when failure persists, restart the reduced configuration and check a completed local deletion boundary.','Both distinguish this retained failure subset from ordinary feature prioritization while acknowledging native tests and interactions.','The retention invariant and condition for one-deletion minimality would be lost under ordinary discretionary variant comparison.','One reduction criterion reorganizes decomposition and its coupled test selection/warrant. Raw task outcomes remain native or uncertain as a distinct observable.','Both keep as sufficient.','Supports an operational rather than vocabulary-based distinction. Minimality is local, test-relative and constrained by valid deletions; budget termination alone is insufficient.'),
'N017':('Partition/removal/complement tests, refinement, reproducibility and final deletion checks coordinate reduction.','Both recognize native task outcomes and some familiar individual trials, while finding the governing search/warrant non-native.','Both condition any minimality claim on completed valid deletion checks, preserving limits at unresolved or budget stops.','D has multiple coordinated rules; raw-observable departure is absent/uncertain.','Both keep as sufficient.','Useful evidence against requiring a new measurement type or real-world usefulness; no global minimum or unique causal explanation is established.'),
'N003':('Ordered event-reference patterns are checked against independent calendars and anchors.','Both honor the archival baseline statement that ordinary pattern comparison is native.','Trial placement shifting alone has no quantitative acceptance or novel evidence rule; both identify lossless reduction.','A uses foreign ring imagery but performs ordinary event chronology.','Both reject.','Supports the distinction between ordinary event matching and the long measured-sequence procedures, without a causal framing test.'),
'N015':('Long measured count runs, offsets and omitted/duplicated increments yield relational alignment evidence.','Both use the explicit baseline distinction that quantitative alignment of long measured sequences is not assumed customary.','Tolerance/anchor-compatible alignments and explicit gap hypotheses would be lost under ordinary clue comparison.','The C is observable-primary, but measurement necessarily entails an operation and a bounded warrant; decomposition is absent/uncertain.','Both keep as sufficient despite ordinary next inquiry.','Supports retention of relational evidence; does not establish a perfectly pure single-field observable effect or actual unique dating.'),
'N009':('Competing offsets and gaps are constrained jointly across the overlap system, with one discriminating anchor check.','Both accept joint quantitative reconstruction as a departure. A calls anchor selection native; B uncertain, and B can overstate native practice as merely per-document.','Global consistency can rule out otherwise locally plausible matches; that constraint is irreducible in both responses.','D coordinates observations and decomposition, without requiring independent next-inquiry novelty.','Both keep as sufficient.','Supports a coordinated transfer while revealing ambiguity about whether changing the objects of an otherwise ordinary follow-up changes that locus.')}

def main():
 r.frozen('anti-collapse',True);r.check_commit('anti-collapse-freeze.json',r.TITLES['anti-collapse'])
 values=r.published('anti-collapse');admissions=r.read(HERE/'admission.json')['cases'];design={x['case_id']:x for x in r.manifest()};ids=sorted({cid for cid,_ in values});reviews=[]
 keys=('operational_distinction','baseline_reading','formalization_and_reduction','single_rule_or_coordination','suppression_or_retention','interpretation')
 for cid in ids:
  row={'case_id':cid,'target_id':design[cid]['target_id'],'design_level':design[cid]['ladder_level'],'statuses':{f:values[(cid,f)]['anti_collapse']['status'] for f in 'AB'},**dict(zip(keys,NOTES[cid]))}
  row['departure_disagreements']={k:{f:values[(cid,f)]['anti_collapse']['departures'][k] for f in 'AB'} for k in r.c.LOCI if values[(cid,'A')]['anti_collapse']['departures'][k]['status']!=values[(cid,'B')]['anti_collapse']['departures'][k]['status']}
  reviews.append(row)
 r.write_new(HERE/'review/case-reviews.json',reviews)
 validity=r.published('validity')
 r.write_new(HERE/'review/validity-review.json',{'family_distributions':{f:{s:sum(v['validity']['final_status']==s for (cid,ff),v in validity.items() if ff==f) for s in ('Valid','Conditional','Invalid')} for f in 'AB'},'status_agreement':{'numerator':sum(validity[(x['case_id'],'A')]['validity']['final_status']==validity[(x['case_id'],'B')]['validity']['final_status'] for x in admissions),'denominator':24},'excluded':[{'admission':x,'design_level':design[x['case_id']]['ladder_level'],'returned_assessments':{f:validity[(x['case_id'],f)]['validity'] for f in 'AB'}} for x in admissions if not x['admitted']],'interpretation':'Four cases excluded without replacement. T04 loses both native controls; T05/T06 lose formalization designs. N018 and N022 expose compressed B descriptions that do not explicitly preserve the complete source chain for family B. Target-fidelity scope remains contested. These are selection limitations, not anti-collapse rejections.'})
 r.write_new(HERE/'review/diagnostics.json',{'locus_disagreements':[{'case_id':row['case_id'],'fields':list(row['departure_disagreements'])} for row in reviews if row['departure_disagreements']], 'action_present_in_all_sufficient':{f:all(v['anti_collapse']['departures']['action']['status']=='present' for (cid,ff),v in values.items() if ff==f and v['anti_collapse']['status']=='SUFFICIENT_DEPARTURE') for f in 'AB'},'explicit_authoring_cue_limit':'Several neutral texts describe their steps as ordinary, say a matrix adds no warrant, or declare preserved units/follow-up. Such statements may make the intended contrasts easy; no wording ablation or natural-output corpus was measured.','representational_limit':'Primary locus means the intended center of one operational rule, not a pure single-field manipulation.','strongest_mechanism_disagreement':'N024: family A retains for request selection; family B for alignment. Neither is adjudicated.','neutralization_audit_result':'All 24 exact operational correspondences and six premeasurement checks pass. This is same-operator textual equivalence, not independent semantic validation.'})
if __name__=='__main__':main()
